name: Generate windows mmt artifacts

# on events
on: [push, pull_request]

# workflow tasks
jobs:
    generate:
        name: Generate cross-platform builds
        runs-on: ubuntu-latest
        steps:
            - name: Checkout the repository
              uses: actions/checkout@v2
            - name: Generate build files
              uses: thatisuday/go-cross-build@v1
              with:
                  platforms: "windows/amd64"
                  package: ""
                  name: "mmt"
                  compress: "false"
                  dest: "dist-win"
            - name: Upload assets
              uses: actions/upload-artifact@v2
              with:
                  name: mmt-win
                  path: dist-win/*
